# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/victoria/http-server-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/victoria/http-server-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victoria/http-server-cpp/CMakeFiles /home/victoria/http-server-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victoria/http-server-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named boost_api_server

# Build rule for target.
boost_api_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_api_server
.PHONY : boost_api_server

# fast build rule for target.
boost_api_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/build
.PHONY : boost_api_server/fast

src/auth.o: src/auth.cpp.o
.PHONY : src/auth.o

# target to build an object file
src/auth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/auth.cpp.o
.PHONY : src/auth.cpp.o

src/auth.i: src/auth.cpp.i
.PHONY : src/auth.i

# target to preprocess a source file
src/auth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/auth.cpp.i
.PHONY : src/auth.cpp.i

src/auth.s: src/auth.cpp.s
.PHONY : src/auth.s

# target to generate assembly for a file
src/auth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/auth.cpp.s
.PHONY : src/auth.cpp.s

src/common.o: src/common.cpp.o
.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/handler_request.o: src/handler_request.cpp.o
.PHONY : src/handler_request.o

# target to build an object file
src/handler_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/handler_request.cpp.o
.PHONY : src/handler_request.cpp.o

src/handler_request.i: src/handler_request.cpp.i
.PHONY : src/handler_request.i

# target to preprocess a source file
src/handler_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/handler_request.cpp.i
.PHONY : src/handler_request.cpp.i

src/handler_request.s: src/handler_request.cpp.s
.PHONY : src/handler_request.s

# target to generate assembly for a file
src/handler_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/handler_request.cpp.s
.PHONY : src/handler_request.cpp.s

src/handlers.o: src/handlers.cpp.o
.PHONY : src/handlers.o

# target to build an object file
src/handlers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/handlers.cpp.o
.PHONY : src/handlers.cpp.o

src/handlers.i: src/handlers.cpp.i
.PHONY : src/handlers.i

# target to preprocess a source file
src/handlers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/handlers.cpp.i
.PHONY : src/handlers.cpp.i

src/handlers.s: src/handlers.cpp.s
.PHONY : src/handlers.s

# target to generate assembly for a file
src/handlers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/handlers.cpp.s
.PHONY : src/handlers.cpp.s

src/input_utils.o: src/input_utils.cpp.o
.PHONY : src/input_utils.o

# target to build an object file
src/input_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/input_utils.cpp.o
.PHONY : src/input_utils.cpp.o

src/input_utils.i: src/input_utils.cpp.i
.PHONY : src/input_utils.i

# target to preprocess a source file
src/input_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/input_utils.cpp.i
.PHONY : src/input_utils.cpp.i

src/input_utils.s: src/input_utils.cpp.s
.PHONY : src/input_utils.s

# target to generate assembly for a file
src/input_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/input_utils.cpp.s
.PHONY : src/input_utils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/password_utils.o: src/password_utils.cpp.o
.PHONY : src/password_utils.o

# target to build an object file
src/password_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/password_utils.cpp.o
.PHONY : src/password_utils.cpp.o

src/password_utils.i: src/password_utils.cpp.i
.PHONY : src/password_utils.i

# target to preprocess a source file
src/password_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/password_utils.cpp.i
.PHONY : src/password_utils.cpp.i

src/password_utils.s: src/password_utils.cpp.s
.PHONY : src/password_utils.s

# target to generate assembly for a file
src/password_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/password_utils.cpp.s
.PHONY : src/password_utils.cpp.s

src/patient_menu.o: src/patient_menu.cpp.o
.PHONY : src/patient_menu.o

# target to build an object file
src/patient_menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/patient_menu.cpp.o
.PHONY : src/patient_menu.cpp.o

src/patient_menu.i: src/patient_menu.cpp.i
.PHONY : src/patient_menu.i

# target to preprocess a source file
src/patient_menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/patient_menu.cpp.i
.PHONY : src/patient_menu.cpp.i

src/patient_menu.s: src/patient_menu.cpp.s
.PHONY : src/patient_menu.s

# target to generate assembly for a file
src/patient_menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/patient_menu.cpp.s
.PHONY : src/patient_menu.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/session.o: src/session.cpp.o
.PHONY : src/session.o

# target to build an object file
src/session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/session.cpp.o
.PHONY : src/session.cpp.o

src/session.i: src/session.cpp.i
.PHONY : src/session.i

# target to preprocess a source file
src/session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/session.cpp.i
.PHONY : src/session.cpp.i

src/session.s: src/session.cpp.s
.PHONY : src/session.s

# target to generate assembly for a file
src/session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/session.cpp.s
.PHONY : src/session.cpp.s

src/super_admin_menu.o: src/super_admin_menu.cpp.o
.PHONY : src/super_admin_menu.o

# target to build an object file
src/super_admin_menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/super_admin_menu.cpp.o
.PHONY : src/super_admin_menu.cpp.o

src/super_admin_menu.i: src/super_admin_menu.cpp.i
.PHONY : src/super_admin_menu.i

# target to preprocess a source file
src/super_admin_menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/super_admin_menu.cpp.i
.PHONY : src/super_admin_menu.cpp.i

src/super_admin_menu.s: src/super_admin_menu.cpp.s
.PHONY : src/super_admin_menu.s

# target to generate assembly for a file
src/super_admin_menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_api_server.dir/build.make CMakeFiles/boost_api_server.dir/src/super_admin_menu.cpp.s
.PHONY : src/super_admin_menu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... boost_api_server"
	@echo "... src/auth.o"
	@echo "... src/auth.i"
	@echo "... src/auth.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/handler_request.o"
	@echo "... src/handler_request.i"
	@echo "... src/handler_request.s"
	@echo "... src/handlers.o"
	@echo "... src/handlers.i"
	@echo "... src/handlers.s"
	@echo "... src/input_utils.o"
	@echo "... src/input_utils.i"
	@echo "... src/input_utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/password_utils.o"
	@echo "... src/password_utils.i"
	@echo "... src/password_utils.s"
	@echo "... src/patient_menu.o"
	@echo "... src/patient_menu.i"
	@echo "... src/patient_menu.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/session.o"
	@echo "... src/session.i"
	@echo "... src/session.s"
	@echo "... src/super_admin_menu.o"
	@echo "... src/super_admin_menu.i"
	@echo "... src/super_admin_menu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

